'use client'

import { useState } from 'react'
import { useLanguage } from '@/lib/i18n/LanguageProvider'

interface IslandOption { id: string; name: string; slug: string }

interface TripPlan {
  title: string
  summary: string
  days: { day: number; title: string; activities: string[] }[]
  tips: string[]
}

export function TripPlannerClient({ islands }: { islands: IslandOption[] }) {
  const { locale } = useLanguage()
  const [days, setDays] = useState(5)
  const [adults, setAdults] = useState(2)
  const [budgetLevel, setBudgetLevel] = useState<'budget' | 'mid' | 'luxury'>('mid')
  const [style, setStyle] = useState<'romantic' | 'family' | 'adventure' | 'nightlife' | 'relax'>('relax')
  const [islandSlug, setIslandSlug] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [plan, setPlan] = useState<TripPlan | null>(null)

  const t = {
    days: locale === 'en' ? 'Number of Days' : locale === 'el' ? 'Αριθμός Ημερών' : 'Gün Sayısı',
    adults: locale === 'en' ? 'Number of Adults' : locale === 'el' ? 'Αριθμός Ενηλίκων' : 'Yetişkin Sayısı',
    budgetLevel: locale === 'en' ? 'Budget Level' : locale === 'el' ? 'Επίπεδο Προϋπολογισμού' : 'Bütçe Seviyesi',
    budgetOptions: {
      budget: locale === 'en' ? '💰 Budget Friendly' : locale === 'el' ? '💰 Οικονομικό' : '💰 Bütçe Dostu',
      mid: locale === 'en' ? '💳 Mid-Range' : locale === 'el' ? '💳 Μεσαία Κατηγορία' : '💳 Orta Segment',
      luxury: locale === 'en' ? '💎 Luxury' : locale === 'el' ? '💎 Πολυτελές' : '💎 Lüks',
    },
    travelStyle: locale === 'en' ? 'Travel Style' : locale === 'el' ? 'Στυλ Ταξιδιού' : 'Seyahat Tarzı',
    styleOptions: {
      relax: locale === 'en' ? '🧘 Calm / Relaxation' : locale === 'el' ? '🧘 Ηρεμία / Χαλάρωση' : '🧘 Sakin / Dinlenme',
      romantic: locale === 'en' ? '💕 Romantic / Honeymoon' : locale === 'el' ? '💕 Ρομαντικό / Μήνας Μέλιτος' : '💕 Romantik / Balayı',
      family: locale === 'en' ? '👨‍👩‍👧 Family Friendly' : locale === 'el' ? '👨‍👩‍👧 Φιλικό για Οικογένειες' : '👨‍👩‍👧 Aile Dostu',
      adventure: locale === 'en' ? '🏄 Adventure / Activity' : locale === 'el' ? '🏄 Περιπέτεια / Δραστηριότητα' : '🏄 Macera / Aktivite',
      nightlife: locale === 'en' ? '🎉 Nightlife' : locale === 'el' ? '🎉 Νυχτερινή Ζωή' : '🎉 Gece Hayatı',
    },
    islandPreference: locale === 'en' ? 'Island Preference' : locale === 'el' ? 'Προτίμηση Νησιού' : 'Ada Tercihi',
    noPreference: locale === 'en' ? "Doesn't matter, suggest one" : locale === 'el' ? 'Δεν έχει σημασία, προτείνετε' : 'Fark etmez, öner',
    planning: locale === 'en' ? 'Planning...' : locale === 'el' ? 'Σχεδιασμός...' : 'Planlanıyor...',
    createPlan: locale === 'en' ? '✨ Create My Trip Plan' : locale === 'el' ? '✨ Δημιουργία Προγράμματος Ταξιδιού' : '✨ Gezi Planımı Oluştur',
    genericError: locale === 'en' ? 'An error occurred.' : locale === 'el' ? 'Παρουσιάστηκε σφάλμα.' : 'Bir hata oluştu.',
    serverUnreachable: locale === 'en' ? 'Could not reach the server.' : locale === 'el' ? 'Δεν ήταν δυνατή η σύνδεση με τον διακομιστή.' : 'Sunucuya ulaşılamadı.',
    emptyStateText: locale === 'en'
      ? 'Choose your preferences and let AI prepare a custom trip plan for you.'
      : locale === 'el'
      ? 'Επιλέξτε τις προτιμήσεις σας και αφήστε την τεχνητή νοημοσύνη να ετοιμάσει ένα εξατομικευμένο πρόγραμμα ταξιδιού για εσάς.'
      : 'Tercihlerini seç, yapay zeka sana özel bir gezi planı hazırlasın.',
    loadingText: locale === 'en' ? 'AI is thinking about the best route for you...' : locale === 'el' ? 'Η τεχνητή νοημοσύνη σκέφτεται την καλύτερη διαδρομή για εσάς...' : 'Yapay zeka senin için en iyi rotayı düşünüyor...',
    dayLabel: (day: number) => locale === 'en' ? `Day ${day}:` : locale === 'el' ? `Ημέρα ${day}:` : `Gün ${day}:`,
    tips: locale === 'en' ? '💡 Tips' : locale === 'el' ? '💡 Συμβουλές' : '💡 İpuçları',
    footnote: locale === 'en'
      ? 'This plan was generated by AI, we recommend confirming actual reservation/opening hours.'
      : locale === 'el'
      ? 'Αυτό το πρόγραμμα δημιουργήθηκε από τεχνητή νοημοσύνη, συνιστούμε να επιβεβαιώσετε τις πραγματικές κρατήσεις/ώρες λειτουργίας.'
      : 'Bu plan yapay zeka tarafından oluşturulmuştur, gerçek rezervasyon/açılış saatlerini kontrol etmenizi öneririz.',
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)
    setPlan(null)

    try {
      const res = await fetch('/api/trip-planner', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ days, adults, budgetLevel, style, islandSlug: islandSlug || undefined }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data.error ?? t.genericError)
      } else {
        setPlan(data.plan)
      }
    } catch {
      setError(t.serverUnreachable)
    }
    setLoading(false)
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <form onSubmit={handleSubmit} className="bg-white dark:bg-neutral-900 p-6 rounded-2xl border border-slate-100 dark:border-neutral-900 shadow-sm h-fit space-y-5">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-bold text-neutral-400 uppercase tracking-wider mb-2">{t.days}</label>
            <input type="number" min={1} max={14} value={days} onChange={(e) => setDays(Number(e.target.value))}
              className="w-full rounded-xl border border-slate-200 dark:border-neutral-800 bg-slate-50 dark:bg-neutral-950 py-2.5 px-4 text-sm outline-none focus:border-sky-500" />
          </div>
          <div>
            <label className="block text-xs font-bold text-neutral-400 uppercase tracking-wider mb-2">{t.adults}</label>
            <input type="number" min={1} value={adults} onChange={(e) => setAdults(Number(e.target.value))}
              className="w-full rounded-xl border border-slate-200 dark:border-neutral-800 bg-slate-50 dark:bg-neutral-950 py-2.5 px-4 text-sm outline-none focus:border-sky-500" />
          </div>
        </div>

        <div>
          <label className="block text-xs font-bold text-neutral-400 uppercase tracking-wider mb-2">{t.budgetLevel}</label>
          <select value={budgetLevel} onChange={(e) => setBudgetLevel(e.target.value as typeof budgetLevel)}
            className="w-full rounded-xl border border-slate-200 dark:border-neutral-800 bg-slate-50 dark:bg-neutral-950 py-2.5 px-4 text-sm outline-none focus:border-sky-500">
            <option value="budget">{t.budgetOptions.budget}</option>
            <option value="mid">{t.budgetOptions.mid}</option>
            <option value="luxury">{t.budgetOptions.luxury}</option>
          </select>
        </div>

        <div>
          <label className="block text-xs font-bold text-neutral-400 uppercase tracking-wider mb-2">{t.travelStyle}</label>
          <select value={style} onChange={(e) => setStyle(e.target.value as typeof style)}
            className="w-full rounded-xl border border-slate-200 dark:border-neutral-800 bg-slate-50 dark:bg-neutral-950 py-2.5 px-4 text-sm outline-none focus:border-sky-500">
            <option value="relax">{t.styleOptions.relax}</option>
            <option value="romantic">{t.styleOptions.romantic}</option>
            <option value="family">{t.styleOptions.family}</option>
            <option value="adventure">{t.styleOptions.adventure}</option>
            <option value="nightlife">{t.styleOptions.nightlife}</option>
          </select>
        </div>

        <div>
          <label className="block text-xs font-bold text-neutral-400 uppercase tracking-wider mb-2">{t.islandPreference}</label>
          <select value={islandSlug} onChange={(e) => setIslandSlug(e.target.value)}
            className="w-full rounded-xl border border-slate-200 dark:border-neutral-800 bg-slate-50 dark:bg-neutral-950 py-2.5 px-4 text-sm outline-none focus:border-sky-500">
            <option value="">{t.noPreference}</option>
            {islands.map((i) => <option key={i.id} value={i.slug}>{i.name}</option>)}
          </select>
        </div>

        <button type="submit" disabled={loading}
          className="w-full rounded-xl bg-sky-600 hover:bg-sky-500 py-3 text-sm font-semibold text-white shadow-md transition-colors disabled:opacity-50">
          {loading ? t.planning : t.createPlan}
        </button>

        {error && <p className="text-sm text-red-600">{error}</p>}
      </form>

      <div>
        {!plan && !loading && (
          <div className="py-16 text-center bg-white dark:bg-neutral-900 border border-dashed border-slate-200 dark:border-neutral-800 rounded-2xl">
            <span className="text-4xl">🤖🏝️</span>
            <p className="mt-4 text-sm text-neutral-500">{t.emptyStateText}</p>
          </div>
        )}

        {loading && (
          <div className="py-16 text-center bg-white dark:bg-neutral-900 border border-slate-100 dark:border-neutral-900 rounded-2xl animate-pulse">
            <span className="text-4xl">🤔</span>
            <p className="mt-4 text-sm text-neutral-500">{t.loadingText}</p>
          </div>
        )}

        {plan && (
          <div className="space-y-4">
            <div className="bg-white dark:bg-neutral-900 p-6 rounded-2xl border border-slate-100 dark:border-neutral-900 shadow-sm">
              <h2 className="text-xl font-bold text-neutral-900 dark:text-white">{plan.title}</h2>
              <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">{plan.summary}</p>
            </div>

            {plan.days.map((d) => (
              <div key={d.day} className="bg-white dark:bg-neutral-900 p-5 rounded-2xl border border-slate-100 dark:border-neutral-900 shadow-sm">
                <h3 className="text-sm font-bold text-sky-600 dark:text-sky-400 uppercase tracking-wider mb-2">{t.dayLabel(d.day)} {d.title}</h3>
                <ul className="space-y-1.5 text-sm text-neutral-700 dark:text-neutral-300">
                  {d.activities.map((a, i) => <li key={i}>• {a}</li>)}
                </ul>
              </div>
            ))}

            {plan.tips.length > 0 && (
              <div className="bg-sky-50 dark:bg-sky-950/30 p-5 rounded-2xl">
                <h3 className="text-sm font-bold text-sky-700 dark:text-sky-400 mb-2">{t.tips}</h3>
                <ul className="space-y-1 text-sm text-sky-800 dark:text-sky-300">
                  {plan.tips.map((tip, i) => <li key={i}>• {tip}</li>)}
                </ul>
              </div>
            )}

            <p className="text-[10px] text-neutral-400 text-center">
              {t.footnote}
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
